# Generated by Django 4.0.3 on 2022-03-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField()),
                ('RAM_ROM', models.CharField(max_length=120)),
                ('processor', models.CharField(max_length=50)),
                ('rear_camera', models.CharField(max_length=50)),
                ('front_camera', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=120)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
