# Generated by Django 4.0.3 on 2022-03-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_mobiles_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
