# Generated by Django 4.0.3 on 2022-04-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='staus',
            new_name='status',
        ),
    ]
