# Generated by Django 4.0.3 on 2022-04-05 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_orders_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='expected_delivery_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 21, 4, 41, 300542), null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('orderplaced', 'orderplaced'), ('dispatched', 'dispatched'), ('in_transmit', 'in_transmit'), ('delivered', 'delivered'), ('order_cancelled', 'order_cancelled')], default='orderplaced', max_length=20),
        ),
    ]
